[build]
  command = "npm run build -- --configuration production"
  publish = "dist/local-contact-forms/browser"

[functions]
  directory = "netlify/functions"

[[edge_functions]]
  path = "/*"
  function = "analytics-tracker"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
