[build]
  command = "npm run build -- --configuration production"
  publish = "dist/local-contact-forms/browser"

[functions]
  directory = "netlify/functions"

[build.environment]
  DENO_DEPLOYMENT_ID = "edge-functions"

[[edge_functions]]
  path = "/*"
  function = "log-analytics"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
